### ISSUE TITLE
Missing 0.0.2 and 0.0.3 release tags

### ISSUE THREAD

**Issue by p-decoraid** [raulanatol/camaleon-mandrill#1]
Rubygems shows two releases, it would be good to have corresponding tags in the git repo.

https://rubygems.org/gems/camaleon_mandrill

**Comment by raulanatol** [comment]
A new version is closed (release tag 0.0.4)

**Comment by p-decoraid** [comment]
Thanks, however it would still be good to have tags for 0.0.2 and 0.0.3 :)

**Comment by raulanatol** [comment]
@p-decoraid done! 
Regards.

**Comment by p-decoraid** [comment]
Thanks!
